# Generated by Django 2.2 on 2019-05-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='main_pic',
            field=models.CharField(default=1, max_length=999),
            preserve_default=False,
        ),
    ]
