# Generated by Django 2.2 on 2019-05-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='zip_code',
        ),
    ]
