# Generated by Django 2.2 on 2019-05-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_remove_zipcode_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.Zipcode'),
        ),
    ]
