# Generated by Django 2.2 on 2019-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_auto_20190510_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
