# Generated by Django 2.2.1 on 2019-05-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_auto_20190515_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.IntegerField(),
        ),
    ]
