# Generated by Django 2.2 on 2019-05-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190512_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='seller',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
