# Generated by Django 2.2 on 2019-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_info_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='seller',
            field=models.BooleanField(default=False),
        ),
    ]
