# Generated by Django 2.2.1 on 2019-05-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_search_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='security_question',
        ),
    ]
