# Generated by Django 2.2.1 on 2019-05-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190513_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
