# Generated by Django 2.2.1 on 2019-05-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190513_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='cc_cvc',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='cc_expires',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='credit_card',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
