# Generated by Django 2.2.1 on 2019-05-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190513_2253'),
        ('users', '0010_auto_20190513_2311'),
    ]

    operations = [
    ]
