# Generated by Django 2.2 on 2019-05-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20190514_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='image',
        ),
    ]
