# Generated by Django 2.2.1 on 2019-05-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20190514_1040'),
        ('users', '0012_remove_buyer_image'),
    ]

    operations = [
    ]
