# Generated by Django 2.2 on 2019-05-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20190512_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
