# Generated by Django 2.2 on 2019-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_auto_20190512_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_sold',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
