# Generated by Django 2.2.1 on 2019-05-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_auto_20190514_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
